server:
  port: 8080
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/sate}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
#  flyway:
#    clean-on-validation-error: true
#    locations: classpath:/db/migrations, classpath:/db/seeders